import { StyleSheet } from 'react-native';

export const commonStyles = StyleSheet.create({
  inputContainer: {
    marginBottom: 20,
  },
  imagePreviewContainer: {
    alignItems: 'center',
    marginBottom: 15,
  },
  imagePreviewTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#333',
    marginBottom: 5,
  },
  imagePreview: {
    width: '100%',
    height: 220,
    resizeMode: 'contain',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#eee',
  },
  imageName: {
    fontSize: 14,
    color: '#555',
    marginTop: 5,
  },
  resultItem: {
    backgroundColor: '#f8f9fa',
    padding: 15,
    borderRadius: 8,
    marginBottom: 10,
  },
  resultText: {
    fontSize: 14,
    color: '#555',
    marginBottom: 8,
  },
  boldText: {
    fontWeight: 'bold',
    color: '#333',
  },
  subResultText: {
    fontSize: 13,
    color: '#444',
    marginLeft: 10,
    marginBottom: 3,
  },
  imagesRow: {
    flexDirection: 'row',
    gap: 15,
    marginBottom: 20,
  },
  resultCard: {
    backgroundColor: '#FFFFFF',
    padding: 20,
    borderRadius: 10,
    alignItems: 'center',
  },
  similarityText: {
    fontSize: 18,
    fontWeight: '500',
    color: '#333',
  },
  comparisonText: {
    fontSize: 14,
    color: '#666',
    marginBottom: 10,
    textAlign: 'center',
  },
  similarityMeter: {
    width: '100%',
    height: 20,
    backgroundColor: '#E0E0E0',
    borderRadius: 10,
    overflow: 'hidden',
    marginBottom: 15,
  },
  similarityIndicator: {
    height: '100%',
    backgroundColor: '#4CAF50',
  },
  poseResultContainer: {
    marginTop: 10,
    paddingLeft: 10,
    borderLeftWidth: 2,
    borderLeftColor: '#007AFF',
  },
  poseResultTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#007AFF',
    marginBottom: 5,
  },
  poseResultText: {
    fontSize: 13,
    color: '#444',
    marginBottom: 3,
  },
  detectionResultContainer: {
    marginTop: 10,
    paddingLeft: 10,
    borderLeftWidth: 2,
    borderLeftColor: '#007AFF',
  },
  detectionResultTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#007AFF',
    marginBottom: 5,
  },
  detectionResultText: {
    fontSize: 13,
    color: '#444',
    marginBottom: 3,
  },
  detectionSummary: {
    marginTop: 15,
  },
  audioInfoContainer: {
    backgroundColor: '#f8f9fa',
    padding: 15,
    borderRadius: 8,
    marginBottom: 15,
  },
  audioInfoTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#333',
    marginBottom: 5,
  },
  audioInfoText: {
    fontSize: 14,
    color: '#555',
    marginBottom: 5,
  },
  audioInfoDetails: {
    fontSize: 12,
    color: '#777',
  },
  timestampText: {
    fontSize: 12,
    color: '#777',
    marginBottom: 8,
  },
  tableContainer: {
    marginTop: 10,
    borderWidth: 1,
    borderColor: '#e0e0e0',
    borderRadius: 8,
    overflow: 'hidden',
  },
  tableHeader: {
    flexDirection: 'row',
    backgroundColor: '#f5f5f5',
    paddingVertical: 12,
    paddingHorizontal: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#e0e0e0',
  },
  tableRow: {
    flexDirection: 'row',
    paddingVertical: 10,
    paddingHorizontal: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
    backgroundColor: 'white',
  },
  tableHeaderText: {
    fontWeight: 'bold',
    fontSize: 12,
    color: '#333',
    textAlign: 'center',
  },
  tableCellText: {
    fontSize: 11,
    color: '#555',
    textAlign: 'center',
  },
  timestampColumn: {
    flex: 2,
  },
  categoryColumn: {
    flex: 3,
  },
  confidenceColumn: {
    flex: 1.5,
  },
  faceResultContainer: {
    marginTop: 10,
    paddingLeft: 10,
    borderLeftWidth: 2,
    borderLeftColor: '#007AFF',
  },
  faceResultTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#007AFF',
    marginBottom: 5,
  },
  faceResultText: {
    fontSize: 13,
    color: '#444',
    marginBottom: 3,
  },
  blendshapeText: {
    fontSize: 12,
    color: '#666',
    marginLeft: 10,
  },
  stylizedImagePreview: {
    width: '100%',
    height: 220,
    resizeMode: 'contain',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#eee',
    marginTop: 10,
  },
  imageContainer: {
    position: 'relative',
    width: '100%',
    height: 220,
  },
  maskOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    opacity: 0.6,
  },
  maskOverlayImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'contain',
  },
  pressableOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'transparent',
  },
  pointIndicator: {
    position: 'absolute',
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: '#007AFF',
    borderWidth: 2,
    borderColor: 'white',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.3,
    shadowRadius: 3,
    elevation: 5,
  },
  instructionText: {
    fontSize: 12,
    color: '#666',
    textAlign: 'center',
    fontStyle: 'italic',
    marginTop: 5,
  },
  pointOfInterestText: {
    fontSize: 12,
    color: '#777',
    marginTop: 5,
  },
  maskContainer: {
    marginTop: 10,
    alignItems: 'center',
  },
  maskText: {
    fontSize: 14,
    color: '#555',
    marginBottom: 5,
  },
  maskPreview: {
    width: '100%',
    height: 220,
    resizeMode: 'contain',
    borderWidth: 1,
    borderColor: '#eee',
  },
  toggleContainer: {
    marginBottom: 20,
  },
  toggleLabel: {
    fontSize: 16,
    fontWeight: '600',
    color: '#333',
    marginBottom: 10,
  },
  toggleButtons: {
    flexDirection: 'row',
    borderRadius: 8,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#007AFF',
  },
  toggleButton: {
    flex: 1,
    paddingVertical: 12,
    paddingHorizontal: 16,
    alignItems: 'center',
    backgroundColor: 'white',
  },
  toggleButtonActive: {
    backgroundColor: '#007AFF',
  },
  toggleButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#007AFF',
  },
  toggleButtonTextActive: {
    color: 'white',
  },
  input: {
    flex: 1,
    borderWidth: 1,
    borderColor: '#CCC',
    borderRadius: 8,
    paddingHorizontal: 15,
    paddingVertical: 12,
    marginRight: 10,
    marginBottom: 16,
    fontSize: 16,
    backgroundColor: '#FFF',
  },
  languagesContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  languageChip: {
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 15,
  },
  languageText: {
    color: '#FFFFFF',
    fontWeight: 'bold',
    fontSize: 14,
  },
  categoriesContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  categoryChip: {
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 15,
  },
  categoryText: {
    color: '#FFFFFF',
    fontWeight: 'bold',
    fontSize: 14,
  },
  modelInfoContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 15,
    flexWrap: 'wrap',
  },
  delegateInfo: {
    backgroundColor: '#e0e0e0',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
  },
  delegateText: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#333',
  },
  inputRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  inputRow2: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 10,
  },
  cycleButton: {
    marginLeft: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: '#f0f0f0',
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
    height: 50,
  },
  cycleButtonText: {
    fontSize: 20,
    color: '#333',
  },
  buttonCompare: {
    marginTop: 15,
  },
  embeddingBlock: {
    marginTop: 8,
    marginBottom: 8,
    backgroundColor: '#f4f4f4',
    borderRadius: 6,
    padding: 8,
    maxHeight: 60,
  },
  embeddingText: {
    fontFamily: 'Menlo',
    fontSize: 11,
    color: '#333',
  },
});
